name: Built with Eleventy
description: Show off your Eleventy site on the Eleventy documentation
title: "[Built with Eleventy] I built something!"
labels: built-with-eleventy
body:
  - type: input
    id: domain
    attributes:
      label: Domain name
      description: The home page of the live web site you built. _[parser:url]_
      placeholder: ex. dropbox.com
    validations:
      required: true
  - type: textarea
    id: tfa
    attributes:
      label: 2FA method
      description: supported 2fa methods
      placeholder: ex. totp
    validations:
      required: false
  - type: input
    id: documentaion
    attributes:
      label: Documentaion
      description: optinal
      placeholder: e.g. https://help.zachleat.com/security/2fa
    validations:
      required: false
